### ISSUE TITLE
Sample.py doesn't run on Windows Python 3.11.2

### ISSUE THREAD

**Issue by kotenok2000** [loda-lang/loda-python#6]
E:\git\loda-python\env\Scripts\activate.bat

(env) E:\git\loda-python>pip install -r requirements.txt
Ignoring tensorflow-macos: markers 'sys_platform == "darwin"' don't match your environment
Requirement already satisfied: nose2 in e:\git\loda-python\env\lib\site-packages (from -r requirements.txt (line 1)) (0.12.0)
Requirement already satisfied: parameterized in e:\git\loda-python\env\lib\site-packages (from -r requirements.txt (line 2)) (0.8.1)
Requirement already satisfied: tensorflow in e:\git\loda-python\env\lib\site-packages (from -r requirements.txt (line 3)) (2.12.0rc0)
Requirement already satisfied: tensorflow-intel==2.12.0-rc0 in e:\git\loda-python\env\lib\site-packages (from tensorflow->-r requirements.txt (line 3)) (2.12.0rc0)
Requirement already satisfied: absl-py>=1.0.0 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (1.6.3)
Requirement already satisfied: flatbuffers>=2.0 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (23.3.3)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (3.8.0)
Requirement already satisfied: jax>=0.3.15 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (0.4.5)
Requirement already satisfied: libclang>=13.0.0 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (15.0.6.1)
Requirement already satisfied: numpy<1.24,>=1.22 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (1.23.5)
Requirement already satisfied: opt-einsum>=2.3.2 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (3.3.0)
Requirement already satisfied: packaging in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (23.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (4.22.0)
Requirement already satisfied: setuptools in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (65.5.0)
Requirement already satisfied: six>=1.12.0 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (2.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (4.5.0)
Requirement already satisfied: wrapt>=1.11.0 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (1.51.3)
Requirement already satisfied: tensorboard<2.13,>=2.12 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (2.12.0)
Requirement already satisfied: tensorflow-estimator<2.13,>=2.12.0rc0 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (2.12.0rc0)
Requirement already satisfied: keras<2.13,>=2.12.0rc0 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (2.12.0rc1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in e:\git\loda-python\env\lib\site-packages (from tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (0.31.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in e:\git\loda-python\env\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (0.38.4)
Requirement already satisfied: scipy>=1.5 in e:\git\loda-python\env\lib\site-packages (from jax>=0.3.15->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (1.10.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in e:\git\loda-python\env\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (2.16.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in e:\git\loda-python\env\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (0.4.6)
Requirement already satisfied: markdown>=2.6.8 in e:\git\loda-python\env\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (3.4.1)
Requirement already satisfied: requests<3,>=2.21.0 in e:\git\loda-python\env\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (2.28.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in e:\git\loda-python\env\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (0.7.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in e:\git\loda-python\env\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in e:\git\loda-python\env\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (2.2.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in e:\git\loda-python\env\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (5.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in e:\git\loda-python\env\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in e:\git\loda-python\env\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in e:\git\loda-python\env\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\git\loda-python\env\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in e:\git\loda-python\env\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in e:\git\loda-python\env\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in e:\git\loda-python\env\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (2022.12.7)
Requirement already satisfied: MarkupSafe>=2.1.1 in e:\git\loda-python\env\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (2.1.2)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in e:\git\loda-python\env\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in e:\git\loda-python\env\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0-rc0->tensorflow->-r requirements.txt (line 3)) (3.2.2)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(env) E:\git\loda-python>python3 sample.py
Python
(env) E:\git\loda-python>python3 .\sample.py
Python
(env) E:\git\loda-python>

(env) E:\git\loda-python>sample.py
; A000040: The prime numbers.
; 2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113,127,131,137,139,149,151,157,163,167,173,179,181,191,193,197,199,211,223,227,229,233,239,241,251,257,263,269,271,277,281,283,293,307,311,313,317,331,337,347,349,353,359,367,373,379,383,389,397,401,409,419,421,431,433,439,443,449,457,461,463,467,479,487,491,499,503,509,521,523,541

mov $1,$0
mul $1,2
max $1,1
sub $1,2
mov $2,4
mov $3,$1
pow $3,4
lpb $3
  max $4,$2
  seq $4,80339 ; Characteristic function of {1} union {primes}: 1 if n is 1 or a prime, else 0.
  mul $4,2
  sub $1,$4
  add $2,2
  sub $3,$1
lpe
add $1,$2
sub $1,1
mov $0,$1

Evaluated to sequence: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71]

Model Tokens: ListWrapper(['nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0', 'mov', '$1', '4', 'add', '$1', '$0', 'pow', '$1', '$0', 'mov', '$0', '$1', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0', 'add', '$0', '1', 'lpb', '$0', '1', 'gcd', '$2', '2', 'mov', '$3', '$0', 'div', '$3', '3', 'lpb', '$3', '1', 'mov', '$1', '$0', 'mod', '$1', '$2', 'add', '$2', '1', 'sub', '$3', '$1', 'lpe', '0', '0', 'div', '$0', '$2', 'pow', '$0', '2', 'mov', '$2', '1', 'lpe', '0', '0', 'mov', '$0', '$2', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0', 'mov', '$1', '6', 'mov', '$2', '2', 'mov', '$3', '3', 'mov', '$4', '4', 'sub', '$0', '3', 'lpb', '$0', '1', 'sub', '$0', '1', 'mov', '$5', '$1', 'add', '$1', '$2', 'mov', '$2', '$3', 'mov', '$3', '$4', 'mov', '$4', '$5', 'lpe', '0', '0', 'add', '$0', '$4', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0', 'mov', '$1', '2', 'mov', '$3', '-1', 'lpb', '$0', '1', 'sub', '$0', '1', 'mov', '$2', '$3', 'mul', '$3', '4', 'add', '$3', '$1', 'mov', '$1', '$2', 'lpe', '0', '0', 'pow', '$3', '2', 'mov', '$0', '$3', 'mul', '$0', '4', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0', 'mul', '$0', '2', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0', 'mov', '$1', '$0', 'mul', '$1', '2', 'max', '$1', '1', 'sub', '$1', '2', 'mov', '$2', '4', 'mov', '$3', '$1', 'pow', '$3', '4', 'lpb', '$3', '1', 'max', '$4', '$2', 'seq', '$4', '80339', 'mul', '$4', '2', 'sub', '$1', '$4', 'add', '$2', '2', 'sub', '$3', '$1', 'lpe', '0', '0', 'add', '$1', '$2', 'sub', '$1', '1', 'mov', '$0', '$1', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0', 'mul', '$0', '2', 'max', '$0', '1', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0', 'mov', '$2', '3', 'lpb', '$0', '1', 'sub', '$0', '1', 'add', '$3', '$2', 'sub', '$3', '2', 'add', '$1', '$3', 'mov', '$2', '$1', 'add', '$4', '$1', 'add', '$3', '$4', 'lpe', '0', '0', 'mov', '$0', '$1', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0', 'add', '$0', '1', 'mov', '$2', '$0', 'mul', '$2', '2', 'lpb', '$0', '1', 'mov', '$3', '$2', 'dif', '$3', '$0', 'sub', '$0', '2', 'cmp', '$3', '$2', 'cmp', '$3', '0', 'add', '$4', '$3', 'lpe', '0', '0', 'mov', '$0', '$4', 'add', '$0', '1', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0', 'mov', '$1', '1', 'lpb', '$0', '1', 'sub', '$0', '1', 'add', '$2', '$1', 'add', '$1', '$2', 'add', '$2', '$1', 'lpe', '0', '0', 'mov', '$0', '$1', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0', 'pow', '$0', '2', 'mod', '$0', '100', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0', 'mov', '$1', '4', 'pow', '$1', '$0', 'div', '$1', '3', 'mul', '$1', '2', 'add', '$1', '1', 'mov', '$0', '$1', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0', 'mul', '$0', '2', 'add', '$0', '1', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0', 'add', '$0', '2', 'mov', '$1', '$0', 'mul', '$0', '2', 'div', '$0', '5', 'div', '$1', '2', 'sub', '$1', '$0', 'mov', '$0', '$1', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0', 'mov', '$2', '$0', 'add', '$2', '1', 'mov', '$3', '$0', 'lpb', '$2', '1', 'mov', '$0', '$3', 'sub', '$2', '1', 'sub', '$0', '$2', 'add', '$4', '1', 'mov', '$5', '$0', 'add', '$5', '$0', 'bin', '$5', '$0', 'div', '$5', '$4', 'add', '$1', '$5', 'lpe', '0', '0', 'mov', '$0', '$1', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0'])

Vocabulary: ListWrapper(['$0', '$1', '$2', '$3', '$4', '$5', '-1', '0', '1', '100', '2', '3', '4', '5', '6', '80339', 'add', 'bin', 'cmp', 'dif', 'div', 'gcd', 'lpb', 'lpe', 'max', 'mod', 'mov', 'mul', 'nop', 'pow', 'seq', 'sub'])

Model IDs: [29  8  8 29  8  8 29  8  8 27  2 13 17  2  1 30  2  1 27  1  2 29  8  8
 29  8  8 29  8  8 17  1  9 23  1  9 22  3 11 27  4  1 21  4 12 23  4  9
 27  2  1 26  2  3 17  3  9 32  4  2 24  8  8 21  1  3 30  1 11 27  3  9
 24  8  8 27  1  3 29  8  8 29  8  8 29  8  8 27  2 15 27  3 11 27  4 12
 27  5 13 32  1 12 23  1  9 32  1  9 27  6  2 17  2  3 27  3  4 27  4  5
 27  5  6 24  8  8 17  1  5 29  8  8 29  8  8 29  8  8 27  2 11 27  4  7
 23  1  9 32  1  9 27  3  4 28  4 13 17  4  2 27  2  3 24  8  8 30  4 11
 27  1  4 28  1 13 29  8  8 29  8  8 29  8  8 28  1 11 29  8  8 29  8  8
 29  8  8 27  2  1 28  2 11 25  2  9 32  2 11 27  3 13 27  4  2 30  4 13
 23  4  9 25  5  3 31  5 16 28  5 11 32  2  5 17  3 11 32  4  2 24  8  8
 17  2  3 32  2  9 27  1  2 29  8  8 29  8  8 29  8  8 28  1 11 25  1  9
 29  8  8 29  8  8 29  8  8 27  3 12 23  1  9 32  1  9 17  4  3 32  4 11
 17  2  4 27  3  2 17  5  2 17  4  5 24  8  8 27  1  2 29  8  8 29  8  8
 29  8  8 17  1  9 27  3  1 28  3 11 23  1  9 27  4  3 20  4  1 32  1 11
 19  4  3 19  4  8 17  5  4 24  8  8 27  1  5 17  1  9 29  8  8 29  8  8
 29  8  8 27  2  9 23  1  9 32  1  9 17  3  2 17  2  3 17  3  2 24  8  8
 27  1  2 29  8  8 29  8  8 29  8  8 30  1 11 26  1 10 29  8  8 29  8  8
 29  8  8 27  2 13 30  2  1 21  2 12 28  2 11 17  2  9 27  1  2 29  8  8
 29  8  8 29  8  8 28  1 11 17  1  9 29  8  8 29  8  8 29  8  8 17  1 11
 27  2  1 28  1 11 21  1 14 21  2 11 32  2  1 27  1  2 29  8  8 29  8  8
 29  8  8 27  3  1 17  3  9 27  4  1 23  3  9 27  1  4 32  3  9 32  1  3
 17  5  9 27  6  1 17  6  1 18  6  1 21  6  5 17  2  6 24  8  8 27  1  2
 29  8  8 29  8  8 29  8  8]

Input: ['nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0']
Label: ['0', '0', 'nop', '0', '0', 'nop', '0', '0', 'mov']

Input: ['$1', '4', 'add', '$1', '$0', 'pow', '$1', '$0', 'mov']
Label: ['4', 'add', '$1', '$0', 'pow', '$1', '$0', 'mov', '$0']

Input: ['$1', 'nop', '0', '0', 'nop', '0', '0', 'nop', '0']
Label: ['nop', '0', '0', 'nop', '0', '0', 'nop', '0', '0']

(16, 9, 33) # (batch_size, sequence_length, vocab_size)
Model: "keras_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 string_lookup (StringLookup  multiple                 0
 )

 string_lookup_1 (StringLook  multiple                 0
 up)

 embedding (Embedding)       multiple                  8448

 gru (GRU)                   multiple                  3938304

 dense (Dense)               multiple                  33825

=================================================================
Total params: 3,980,577
Trainable params: 3,980,577
Non-trainable params: 0
_________________________________________________________________
Input: ['$0', '100', 'nop', '0', '0', 'nop', '0', '0', 'nop']
Predictions: ['1', '$1', '6', '80339', '1', '$1', 'pow', 'seq', 'add']
Prediction shape:  (16, 9, 33)  # (batch_size, sequence_length, vocab_size)
Mean loss:         tf.Tensor(3.4941952, shape=(), dtype=float32)
Exp Mean loss:     32.923782
Vocabulary Size:   33
Epoch 1/10
3/3 [==============================] - ETA: 0s - loss: 3.4353Traceback (most recent call last):
  File "E:\git\loda-python\sample.py", line 67, in <module>
    sample.keras_model()
  File "E:\git\loda-python\sample.py", line 60, in keras_model
    model.fit_with_checkpoints(10, "training_checkpoints")
  File "E:\git\loda-python\loda\ml\keras_model.py", line 83, in fit_with_checkpoints
    return self.fit(self.prefetch_dataset, epochs=epochs, callbacks=[checkpoint_callback])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\git\loda-python\env\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "e:\git\loda-python\env\Lib\site-packages\tensorflow\python\trackable\data_structures.py", line 823, in __getattribute__
    return super().__getattribute__(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: this __dict__ descriptor does not support '_DictWrapper' objects

**Comment by ckrause** [comment]
Can you please try it with the latest version?

**Comment by kotenok2000** [comment]
It displays this after git pull.
[Текстовый документ.txt](https://github.com/loda-lang/loda-python/files/11072022/default.txt)
